//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace küytüphane_otomasyonu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("küytüphane_otomasyonu.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string AdiSoyadi {
            get {
                return ResourceManager.GetString("AdiSoyadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string Adsoyad {
            get {
                return ResourceManager.GetString("Adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alıcı Adı.
        /// </summary>
        internal static string Alici {
            get {
                return ResourceManager.GetString("Alici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliciTc.
        /// </summary>
        internal static string AliciTc {
            get {
                return ResourceManager.GetString("AliciTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AliciTel.
        /// </summary>
        internal static string AliciTel {
            get {
                return ResourceManager.GetString("AliciTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string btn_Ekle {
            get {
                return ResourceManager.GetString("btn_Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        internal static string btn_giris {
            get {
                return ResourceManager.GetString("btn_giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string btn_guncelle {
            get {
                return ResourceManager.GetString("btn_guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        internal static string btn_kaydol {
            get {
                return ResourceManager.GetString("btn_kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string btn_sil {
            get {
                return ResourceManager.GetString("btn_sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Et.
        /// </summary>
        internal static string btn_TeslimEt {
            get {
                return ResourceManager.GetString("btn_TeslimEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi unuttum.
        /// </summary>
        internal static string btn_unuttum {
            get {
                return ResourceManager.GetString("btn_unuttum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        internal static string btn_uye_kayit {
            get {
                return ResourceManager.GetString("btn_uye_kayit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çevirmen.
        /// </summary>
        internal static string Cevirmenn {
            get {
                return ResourceManager.GetString("Cevirmenn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        internal static string Cinsiyet {
            get {
                return ResourceManager.GetString("Cinsiyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinsiyet.
        /// </summary>
        internal static string Cinsiyett {
            get {
                return ResourceManager.GetString("Cinsiyett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dergi Adı:.
        /// </summary>
        internal static string dergi {
            get {
                return ResourceManager.GetString("dergi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dergi İşlemleri.
        /// </summary>
        internal static string Dergi_islemeri {
            get {
                return ResourceManager.GetString("Dergi_islemeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dergi.
        /// </summary>
        internal static string Dergi2 {
            get {
                return ResourceManager.GetString("Dergi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dili:.
        /// </summary>
        internal static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçimi.
        /// </summary>
        internal static string DilSecimi {
            get {
                return ResourceManager.GetString("DilSecimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi:.
        /// </summary>
        internal static string Dtarih {
            get {
                return ResourceManager.GetString("Dtarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta.
        /// </summary>
        internal static string E_posta {
            get {
                return ResourceManager.GetString("E_posta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emanet Alma.
        /// </summary>
        internal static string EmanetAlma {
            get {
                return ResourceManager.GetString("EmanetAlma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emanet Verme.
        /// </summary>
        internal static string EmanetVerme {
            get {
                return ResourceManager.GetString("EmanetVerme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string İsbn {
            get {
                return ResourceManager.GetString("İsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSN No:.
        /// </summary>
        internal static string İssn {
            get {
                return ResourceManager.GetString("İssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitap Adı.
        /// </summary>
        internal static string Kitap {
            get {
                return ResourceManager.GetString("Kitap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitap İşlemleri.
        /// </summary>
        internal static string Kitap_islemleri {
            get {
                return ResourceManager.GetString("Kitap_islemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta:.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okunanlar.
        /// </summary>
        internal static string okunanlar {
            get {
                return ResourceManager.GetString("okunanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raf no.
        /// </summary>
        internal static string Rafnoo {
            get {
                return ResourceManager.GetString("Rafnoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyonlar.
        /// </summary>
        internal static string Rezervasyonlar {
            get {
                return ResourceManager.GetString("Rezervasyonlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon Yap:.
        /// </summary>
        internal static string Rezz {
            get {
                return ResourceManager.GetString("Rezz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol:.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre:.
        /// </summary>
        internal static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifre .
        /// </summary>
        internal static string SifreAl {
            get {
                return ResourceManager.GetString("SifreAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinenler.
        /// </summary>
        internal static string Silinenler {
            get {
                return ResourceManager.GetString("Silinenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc:.
        /// </summary>
        internal static string Tc {
            get {
                return ResourceManager.GetString("Tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tc.
        /// </summary>
        internal static string Tcc {
            get {
                return ResourceManager.GetString("Tcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türü.
        /// </summary>
        internal static string Turuu {
            get {
                return ResourceManager.GetString("Turuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye İşlemleri.
        /// </summary>
        internal static string Uye_islemleri {
            get {
                return ResourceManager.GetString("Uye_islemleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayın evi.
        /// </summary>
        internal static string YayinEvii {
            get {
                return ResourceManager.GetString("YayinEvii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayın tarihi:.
        /// </summary>
        internal static string YayinTarihi {
            get {
                return ResourceManager.GetString("YayinTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar.
        /// </summary>
        internal static string Yazarr {
            get {
                return ResourceManager.GetString("Yazarr", resourceCulture);
            }
        }
    }
}
