//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace küytüphane_otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dergiler
    {
        public long issn { get; set; }
        public string dergi_adi { get; set; }
        public string dili { get; set; }
        public Nullable<System.DateTime> yayin_tarihi { get; set; }
    }
}
