//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace küytüphane_otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        public string kitap_adi { get; set; }
        public string yayin_evi { get; set; }
        public long isbn { get; set; }
        public string yazar { get; set; }
        public string turu { get; set; }
        public string rafno { get; set; }
        public string cevirmen { get; set; }
    
        public virtual emanetler emanetler { get; set; }
    }
}
