//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace küytüphane_otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public string rol { get; set; }
        public string ad_soyad { get; set; }
        public string sifre { get; set; }
        public string eposta { get; set; }
        public long tc { get; set; }
    }
}
