//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace küytüphane_otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.emanetler = new HashSet<emanetler>();
        }
    
        public long tc { get; set; }
        public string ad_soyad { get; set; }
        public Nullable<System.DateTime> d_tarihi { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<long> tel { get; set; }
        public string adres { get; set; }
        public string eposta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emanetler> emanetler { get; set; }
    }
}
